version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_filter
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: smart_filter_db
    restart: always
    environment:
      MYSQL_DATABASE: smart_filter_app
      MYSQL_USER: smart_filter_user
      MYSQL_PASSWORD: strong_password
      MYSQL_ROOT_PASSWORD: root_strong_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
